clang++ -std=c++11 -stdlib=libc++ -lcurses -D MINIX -D TEST -D CLEAN *.cpp -o main_test
clang++ -std=c++11 -stdlib=libc++ -lcurses -D COMPILING_LOOP InfiniteLoopTest.cpp -o main_loop
clang++ -std=c++11 -stdlib=libc++ -lcurses -D MINIX  *.cpp -o main
clang++ -std=c++11 -stdlib=libc++ -lcurses -D MINIX -D DEBUG -D CLEAN  *.cpp -o main_debug
clang++ -std=c++11 -stdlib=libc++ -lcurses -D MINIX -D DEBUG -D TEST -D CLEAN  *.cpp -o main_test_debug
clang++ -std=c++11 -stdlib=libc++ -lcurses -D MINIX -D DEBUG -D DEBUG_ALARM -D CLEAN *.cpp -o main_debug_alarm
